# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    config.vm.box = "centos/7"
    config.vm.network "private_network", ip: "192.168.0.10"
    config.vm.provision "shell", inline: <<-SHELL
	  echo "webserver" > /etc/hostname
	  hostname -b webserver
	  echo "192.168.0.20		clockserver" >> /etc/hosts
	SHELL
  end
  
  config.vm.define "clock" do |clock|
    config.vm.box = "centos/7"
    config.vm.network "private_network", ip: "192.168.0.20"
    config.vm.provision "shell", inline: <<-SHELL
	  echo "clockserver" > /etc/hostname
	  hostname -b clockserver
	  echo "192.168.0.10		webserver" >> /etc/hosts
	SHELL
  end
end
